# Generated by Django 5.2.6 on 2025-09-28 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('livestock', 'Livestock')], max_length=20)),
                ('crop_name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('sell_by_date', models.DateField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crop_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='crop_listin_categor_a84319_idx'), models.Index(fields=['status'], name='crop_listin_status_0a81af_idx'), models.Index(fields=['sell_by_date'], name='crop_listin_sell_by_869753_idx')],
            },
        ),
    ]
