# Generated by Django 5.2.6 on 2025-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_croplisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplisting',
            name='crop_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
