# Generated by Django 5.2.6 on 2025-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_croplisting_crop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
