# Generated by Django 5.2.6 on 2025-10-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_croplisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplisting',
            name='image',
        ),
    ]
