# Generated by Django 5.2.6 on 2025-09-29 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('province', models.CharField(max_length=3)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('inflation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_harvest_season', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('KZN', 'KwaZulu-Natal'), ('GP', 'Gauteng'), ('WC', 'Western Cape'), ('EC', 'Eastern Cape'), ('NC', 'Northern Cape'), ('FS', 'Free State'), ('MP', 'Mpumalanga'), ('LP', 'Limpopo'), ('NW', 'North West')], max_length=3)),
                ('dataset', models.FileField(upload_to='datasets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('is_initialized', models.BooleanField(default=False)),
                ('last_forecast_date', models.DateTimeField(blank=True, null=True)),
                ('price_model_accuracy', models.FloatField(blank=True, null=True)),
                ('demand_model_accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('crop_name', 'province')},
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_horizon', models.IntegerField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_lower_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_upper_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('demand_lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('demand_upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue_estimate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.forecastingmodel')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('model', 'forecast_date', 'forecast_horizon')},
            },
        ),
    ]
