# Generated by Django 5.2.6 on 2025-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastingmodel',
            name='initialization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='externalfactors',
            unique_together={('date', 'province')},
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['model', 'forecast_horizon', 'forecast_date'], name='forecasting_model_i_36070a_idx'),
        ),
    ]
