# Generated by Django 5.2.6 on 2025-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_forecastingmodel_initialization_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastingmodel',
            name='initialization_status',
        ),
        migrations.AlterField(
            model_name='forecastingmodel',
            name='demand_model_accuracy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forecastingmodel',
            name='price_model_accuracy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
